# -*- mode: ruby -*-
# vi: set ft=ruby :

LINKERD_COUNT = 3

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  (1..LINKERD_COUNT).each do |i|
    config.vm.define "linkerd0#{i}" do |subconfig|
      subconfig.vm.hostname = "linkerd0#{i}"
      subconfig.vm.network :private_network, ip: "192.168.1.#{i + 10}"
      # to access linkerd admin dashboard from local
      subconfig.vm.network :forwarded_port, guest: 9990, host: "#{i + 9990}"
    end
  end

  config.vm.provision "provision", type: "shell", :path => "provision.sh"
end