FROM golang:1.9-alpine3.7 as builder

WORKDIR /go/src/github.com/yangzhares/linkerd-in-action/concert-booking
COPY . .
RUN apk update \
    && apk add --no-cache git \
    && go get -u github.com/golang/dep/cmd/dep \
    && cd bookingservice \
    && go build -v -o booking

FROM openjdk:8-alpine3.7

WORKDIR /app
COPY startup/booking/startup.sh .
COPY --from=builder /go/src/github.com/yangzhares/linkerd-in-action/concert-booking/bookingservice/booking  .
COPY --from=builder /go/src/github.com/yangzhares/linkerd-in-action/concert-booking/bookingservice/config.json .

RUN apk update \
    && apk add --no-cache curl wget bash ca-certificates\
    && wget -qO /app/linkerd-1.3.6-exec https://github.com/linkerd/linkerd/releases/download/1.3.6/linkerd-1.3.6-exec \
    && chmod +x /app/startup.sh /app/linkerd-1.3.6-exec

CMD ["/app/startup.sh"]
