FROM golang:1.9-alpine3.7 as builder

WORKDIR /go/src/github.com/yangzhares/linkerd-in-action/concert-booking
COPY . .
RUN apk update \
    && apk add --no-cache git \
    && go get -u github.com/golang/dep/cmd/dep \
    && cd bookingservice \
    && go build -v -o booking

FROM alpine:3.7

WORKDIR /app
COPY --from=builder /go/src/github.com/yangzhares/linkerd-in-action/concert-booking/bookingservice/booking  .
COPY --from=builder /go/src/github.com/yangzhares/linkerd-in-action/concert-booking/bookingservice/config.json .

RUN apk update \
    && apk add --no-cache wget bash ca-certificates\
    && wget -O /dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 \
    && chmod 755 /dumb-init

ENTRYPOINT ["/dumb-init", "--"]
CMD ["/app/booking"]
