---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config-edge
data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9990
    namers:
    - kind: io.l5d.k8s
      host: localhost
      port: 8001
    - kind: io.l5d.rewrite
      prefix: /portNsSvcToK8s
      pattern: "/{port}/{ns}/{svc}"
      name: "/k8s/{ns}/{port}/{svc}"
    routers:
    - protocol: http
      label: outgoing
      servers:
        - port: 8080
          ip: 127.0.0.1
          clearContext: true
      dtab: |
        /k8s          =>   /#/io.l5d.k8s;
        /portNsSvc    =>   /#/portNsSvcToK8s;
        /host         =>   /portNsSvc/http/default;
        /host         =>   /portNsSvc/http;
        /svc          =>   /$/io.buoyant.http.domainToPathPfx/host; 
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: default
          port: incoming
          service: l5d
          hostNetwork: true
    usage:
      enabled: false
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: l5d-edge
  name: l5d-edge
spec:
  selector:
    matchLabels:
      app: l5d-edge
  template:
    metadata:
      labels:
        app: l5d-edge
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      nodeName: kube-master
      volumes:
      - name: l5d-config-edge
        configMap:
          name: "l5d-config-edge"
      containers:
      - name: l5d-edge
        image: buoyantio/linkerd:1.3.6
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - /io.buoyant/linkerd/config/config.yaml
        ports:
        - name: http
          containerPort: 8080
        - name: admin
          containerPort: 9990
        volumeMounts:
        - name: "l5d-config-edge"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true

      - name: kubectl
        image: zhanyang/kubectl:1.9.3
        args: 
        - "proxy" 
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: l5d-edge
spec:
  selector:
    app: l5d-edge
  clusterIP: None
  ports:
  - name: http
    port: 8080
  - name: admin
    port: 9990